import type { Metadata } from "next";
import { Azeret_Mono } from "next/font/google";
import "./globals.css";


const azeretMono = Azeret_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${azeretMono.className} bg-main-background text-white`}>
        <main className="max-w-[1440px] mx-auto">{children}</main>
      </body>
    </html>
  );
}
